
# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            BeyondBull 
url:              http://www.beyondbull.net
shorturl:         beyondbull.net

paginate:         3

# Custom vars
version:          1.0.0


pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'

